version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - lovechedule-network

  redis:
    image: redis:latest
    container_name: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    networks:
      - lovechedule-network

  lovechedule-server:
    build:
      context: ../../server
      dockerfile: Dockerfile
    image: soomumu/project:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - lovechedule-network

networks:
  lovechedule-network:
    driver: overlay
