version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - lovechedule-network

  redis:
    image: redis:latest
    container_name: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    networks:
      - lovechedule-network

  lovechedule-server:
    build:
      context: ../../server
      dockerfile: Dockerfile
    image: soomumu/project:latest
    environment:
      - MONGO_URL=mongodb://root:1234@mongodb:27017/lovechedule?authSource=admin
      - JWT_ACCESS_TOKEN_SECRET=secret
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=365d
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_EXPIRED_AT=0
      - WEATHER_API_KEY=ec379cdcda47660851b8bd47f8432f8b
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - lovechedule-network

networks:
  lovechedule-network:
    driver: overlay
